fix: properly checks presence of mounted secrets
removes ns from kustomize resources as it will be anyway replaced when running the job

diff --git a/service-mesh/control-plane/base/init-job.yaml b/service-mesh/control-plane/base/init-job.yaml
--- a/service-mesh/control-plane/base/init-job.yaml
+++ b/service-mesh/control-plane/base/init-job.yaml
@@ -74,14 +74,18 @@ spec:
             # Ensure secrets are mounted in ingress-gateway. If not, restart the pod.
             kubectl wait pods -l app=istio-ingressgateway --for condition=ready -n ${ISTIO_NAMESPACE}
 
-            if kubectl exec $(kubectl get pods -n ${ISTIO_NAMESPACE} \
-              -l app=istio-egressgateway \
-              -o jsonpath='{.items[*].metadata.name}') \
-              -n ${ISTIO_NAMESPACE} \
-              -c istio-proxy -- ls -al /etc/istio/odh-oauth2 2>&1 | grep -q 'No such file or directory'; then
+            INGRESS_POD=$(kubectl get pods -n ${ISTIO_NAMESPACE} -l app=istio-ingressgateway -o jsonpath='{.items[0].metadata.name}')
+            EXEC_OUTPUT=$(kubectl exec $INGRESS_POD -n ${ISTIO_NAMESPACE} -c istio-proxy -- ls -al /etc/istio/odh-oauth2/{token-secret.yaml,hmac-secret.yaml} 2>&1)
+            EXEC_EXIT_STATUS=$?
+
+            if echo $EXEC_OUTPUT | grep -q 'No such file or directory'; then
               # If we don't see the secrets mounted, restart deployment.
               kubectl rollout restart deployment -n ${ISTIO_NAMESPACE} istio-ingressgateway
+            elif [[ $EXEC_EXIT_STATUS -ne 0 ]]; then
+              echo "Failed with: $EXEC_OUTPUT"
+              exit 1
             fi
+
             exit 0
             
         volumeMounts:
