fix: resolves ns in init-job (#22)

diff --git a/service-mesh/control-plane/base/init-job.yaml b/service-mesh/control-plane/base/init-job.yaml
--- a/service-mesh/control-plane/base/init-job.yaml
+++ b/service-mesh/control-plane/base/init-job.yaml
@@ -20,6 +20,9 @@ spec:
             curl -L https://github.com/a8m/envsubst/releases/download/v1.2.0/envsubst-`uname -s`-`uname -m` -o /tmp/bin/envsubst && chmod +x /tmp/bin/envsubst
             export PATH=/tmp/bin:$PATH
 
+            export ISTIO_NAMESPACE=$(kubectl get jobs -o jsonpath='{.items[?(@.metadata.name=="odh-ossm-init-job")].metadata.namespace}')
+            export ODH_NAMESPACE=$(kubectl get configmap --all-namespaces -o json | jq -r '.items[] | select(.metadata.name == "odh-common-config") | .metadata.namespace')
+
             export CLIENT_SECRET=$(openssl rand -hex 32)
             export HMAC_SECRET=$(openssl rand -hex 32)
             export DOMAIN=$(kubectl get ingress.config.openshift.io cluster -o 'jsonpath={.spec.domain}')
@@ -39,27 +42,28 @@ spec:
 
               case "$filename" in
                 "/etc/cluster-resources/authconfig.yaml")
-                  namespace="opendatahub"
+                  namespace="${ODH_NAMESPACE}"
                   ;;
                 *)
-                  namespace="istio-system"
+                  namespace="${ISTIO_NAMESPACE}"
                   ;;
               esac
 
               cat "$filename" | envsubst | kubectl apply -n $namespace -f -
             }
 
-            # create secrets for oauth2 (formerly configmap)
-            kubectl create secret generic istio-odh-oauth2 -n istio-system \
+            # recreate secrets for oauth2
+            kubectl delete secret istio-odh-oauth2 -n ${ISTIO_NAMESPACE} --ignore-not-found
+            kubectl create secret generic istio-odh-oauth2 -n ${ISTIO_NAMESPACE} \
                 --from-file=token-secret.yaml=<(envsubst < $TOKEN_FILEPATH) \
                 --from-file=hmac-secret.yaml=<(envsubst < $HMAC_FILEPATH)
 
             # add annotation to the root namespace (hardcoded pre-plugin)
-            kubectl annotate namespace opendatahub opendatahub.io/service-mesh=true
+            kubectl annotate namespace ${ODH_NAMESPACE} opendatahub.io/service-mesh=true
 
             # wait for app to be ready
             echo "waiting for SMCP to be ready"
-            kubectl -n istio-system wait --for=condition=Ready smcp/basic --timeout=180s          
+            kubectl -n ${ISTIO_NAMESPACE} wait --for=condition=Ready smcp/basic --timeout=180s          
 
             # iterate over all files in the subdirectory
             for filename in /etc/cluster-resources/*
@@ -68,16 +72,20 @@ spec:
             done
 
             # Ensure secrets are mounted in ingress-gateway. If not, restart the pod.
-            kubectl wait pods -l app=istio-ingressgateway --for condition=ready -n istio-system
+            kubectl wait pods -l app=istio-ingressgateway --for condition=ready -n ${ISTIO_NAMESPACE}
 
-            if kubectl exec $(kubectl get pods -n istio-system \
-              -l app=istio-egressgateway \
-              -o jsonpath='{.items[*].metadata.name}') \
-              -n istio-system \
-              -c istio-proxy -- ls -al /etc/istio/odh-oauth2 2>&1 | grep -q 'No such file or directory'; then
+            INGRESS_POD=$(kubectl get pods -n ${ISTIO_NAMESPACE} -l app=istio-ingressgateway -o jsonpath='{.items[0].metadata.name}')
+            EXEC_OUTPUT=$(kubectl exec $INGRESS_POD -n ${ISTIO_NAMESPACE} -c istio-proxy -- ls -al /etc/istio/odh-oauth2/{token-secret.yaml,hmac-secret.yaml} 2>&1)
+            EXEC_EXIT_STATUS=$?
+
+            if echo $EXEC_OUTPUT | grep -q 'No such file or directory'; then
               # If we don't see the secrets mounted, restart deployment.
-              kubectl rollout restart deployment -n istio-system istio-ingressgateway
+              kubectl rollout restart deployment -n ${ISTIO_NAMESPACE} istio-ingressgateway
+            elif [[ $EXEC_EXIT_STATUS -ne 0 ]]; then
+              echo "Failed with: $EXEC_OUTPUT"
+              exit 1
             fi
+
             exit 0
             
         volumeMounts:
